
package com.vvirlan;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Main", targetNamespace = "http://vvirlan.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Main {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://vvirlan.com/", className = "com.vvirlan.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://vvirlan.com/", className = "com.vvirlan.SayHelloResponse")
    @Action(input = "http://vvirlan.com/Main/sayHelloRequest", output = "http://vvirlan.com/Main/sayHelloResponse")
    public String sayHello();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayNothing", targetNamespace = "http://vvirlan.com/", className = "com.vvirlan.SayNothing")
    @ResponseWrapper(localName = "sayNothingResponse", targetNamespace = "http://vvirlan.com/", className = "com.vvirlan.SayNothingResponse")
    @Action(input = "http://vvirlan.com/Main/sayNothingRequest", output = "http://vvirlan.com/Main/sayNothingResponse")
    public String sayNothing();

}
