
package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyServiceImpl", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyServiceImpl {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service/", className = "service.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service/", className = "service.SayHelloResponse")
    @Action(input = "http://service/MyServiceImpl/sayHelloRequest", output = "http://service/MyServiceImpl/sayHelloResponse")
    public String sayHello();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "upload", targetNamespace = "http://service/", className = "service.Upload")
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://service/", className = "service.UploadResponse")
    @Action(input = "http://service/MyServiceImpl/uploadRequest", output = "http://service/MyServiceImpl/uploadResponse")
    public String upload(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0);

}
